# Generated by Django 2.0.3 on 2018-05-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file_hashed',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
